### ISSUE TITLE
Taxonomy registration

### ISSUE THREAD

**Issue by ghost** [hiwelo/raccoon-plugin#31]
Would it be possible to add this as a module? I see in the post type specification that you can attach existing taxonomies to a post type, but creating the taxonomy still needs to be done via standard WP functions. It would be great to have all of the taxonomy/post type stuff in the same place.

**Comment by hiwelo** [comment]
Sure, thank you for this enhancement proposal.
I will try to add this in the next release. 😸

**Comment by ghost** [comment]
Awesome, thanks!
